services:
  mongo:
    image: mongo:7
    container_name: shedit-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - shedit-mongo-data:/data/db

volumes:
  shedit-mongo-data:
